version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: user_managment
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin