version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: user_management
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - backend

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT=6379
    networks:
      - backend

  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "pip install alembic && poetry run alembic upgrade head"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - backend

networks:
  backend:
    driver: bridge
