[tool.poetry]
name = "user-managment"
version = "0.1"
description = "User_managment microservice"
authors = ["JustPC <robert49324@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
black = "^24.1.1"
fastapi = "^0.109.0"
isort = "^5.13.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
