# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/grpc.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10proto/grpc.proto\x12\x04grpc"\x88\x01\n\tUserModel\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07surname\x18\x03 \x01(\t\x12\x10\n\x08username\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\x12\x0c\n\x04role\x18\x06 \x01(\t\x12\r\n\x05group\x18\x07 \x01(\x04\x12\x12\n\nis_blocked\x18\x08 \x01(\x08"\x1d\n\x0eGetUserRequest\x12\x0b\n\x03jwt\x18\x01 \x01(\t"0\n\x0fGetUserResponse\x12\x1d\n\x04user\x18\x01 \x01(\x0b\x32\x0f.grpc.UserModel2E\n\x0bUserService\x12\x36\n\x07GetUser\x12\x14.grpc.GetUserRequest\x1a\x15.grpc.GetUserResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "proto.grpc_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_USERMODEL"]._serialized_start = 27
    _globals["_USERMODEL"]._serialized_end = 163
    _globals["_GETUSERREQUEST"]._serialized_start = 165
    _globals["_GETUSERREQUEST"]._serialized_end = 194
    _globals["_GETUSERRESPONSE"]._serialized_start = 196
    _globals["_GETUSERRESPONSE"]._serialized_end = 244
    _globals["_USERSERVICE"]._serialized_start = 246
    _globals["_USERSERVICE"]._serialized_end = 315
# @@protoc_insertion_point(module_scope)
