name: test

on: [push]

jobs:
  testing:
    name: testing
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/src
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DATABASE: "user_management"
      REDIS_URL: "redis://redis:6379"
      REDIS_PORT: "6379"
      RABBITMQ_USER: "user"
      RABBITMQ_PASSWORD: "password"
      LOCALSTACK_URL: "http://localstack:4566"
      AWS_ACCESS_KEY_I: "admin"
      AWS_SECRET_ACCESS_KEY: "admin"
      AWS_BUCKET: "images"
      SECRET_KEY: "DZn7NOmHr15c8e4siT7v1aB4FV5nYmmP"
      ALGORITHM: "HS256"
      HOST: "0.0.0.0"
      PORT: "8000"

    services:
      postgres:
        image: postgres:16-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: user_management
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.1'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Migrations
        run: |
          echo $PYTHONPATH 
          echo $POSTGRES_USER
          echo $POSTGRES_PASSWORD 
          echo $POSTGRES_DATABASE 
          echo $REDIS_URL
          echo $REDIS_PORT 
          echo $RABBITMQ_USER 
          echo $RABBITMQ_PASSWORD 
          echo $LOCALSTACK_URL
          echo $AWS_ACCESS_KEY_I
          echo $AWS_SECRET_ACCESS_KEY 
          echo $AWS_BUCKET 
          echo $SECRET_KEY 
          echo $ALGORITHM
          echo $HOST
          echo $PORT

          poetry run alembic upgrade head

      - name: Run tests
        run: |
          poetry run pytest