name: test

on: [push]

jobs:
  testing:
    name: testing
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: user_management
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      # - name: Migrations
      #   run: |
      #     poetry run alembic upgrade head

      - name: Run tests
        env:
          PG_USER: test
          PG_PASSWORD: test
          PG_HOST: localhost
          PG_PORT: 5432
          PG_DATABASE: test_db
        run: |
          poetry run pytest